# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveluser',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='traveluser',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
