# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180625_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
